BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
        CHECK (role IN ('ADMIN', 'PROFESSOR', 'MEMBER')),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS activities (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS classes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id INTEGER NOT NULL REFERENCES activities(id) ON DELETE RESTRICT,
    professor_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT classes_valid_time CHECK (ends_at > starts_at),
    CONSTRAINT classes_unique_schedule
        UNIQUE (activity_id, professor_id, starts_at)
);

CREATE TABLE IF NOT EXISTS package_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    class_credits INTEGER NOT NULL CHECK (class_credits > 0),
    duration_days INTEGER NOT NULL CHECK (duration_days > 0)
);

CREATE TABLE IF NOT EXISTS member_packages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    package_type_id INTEGER NOT NULL REFERENCES package_types(id) ON DELETE RESTRICT,
    starts_on DATE NOT NULL,
    expires_on DATE NOT NULL,
    remaining_credits INTEGER NOT NULL CHECK (remaining_credits >= 0),
    CONSTRAINT member_packages_valid_dates CHECK (expires_on >= starts_on),
    CONSTRAINT member_packages_unique_assignment
        UNIQUE (member_id, package_type_id, starts_on)
);

CREATE TABLE IF NOT EXISTS class_reservations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id INTEGER NOT NULL REFERENCES classes(id) ON DELETE RESTRICT,
    member_package_id INTEGER NOT NULL REFERENCES member_packages(id) ON DELETE RESTRICT,
    cancelled BOOLEAN NOT NULL DEFAULT FALSE,
    attended BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT class_reservations_unique
        UNIQUE (class_id, member_package_id)
);

CREATE INDEX IF NOT EXISTS classes_starts_at_idx
    ON classes (starts_at);

CREATE INDEX IF NOT EXISTS member_packages_member_id_idx
    ON member_packages (member_id);

CREATE INDEX IF NOT EXISTS class_reservations_class_id_idx
    ON class_reservations (class_id);

INSERT INTO users (name, email, password_hash, role, active)
VALUES
    ('Admin GymFlow', 'admin@gymflow.test', 'DISABLED_SAMPLE_USER', 'ADMIN', TRUE),
    ('Ana Professor', 'ana.professor@gymflow.test', 'DISABLED_SAMPLE_USER', 'PROFESSOR', TRUE),
    ('Juan Member', 'juan.member@gymflow.test', 'DISABLED_SAMPLE_USER', 'MEMBER', TRUE),
    ('Laura Member', 'laura.member@gymflow.test', 'DISABLED_SAMPLE_USER', 'MEMBER', TRUE)
ON CONFLICT (email) DO UPDATE
SET name = EXCLUDED.name,
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    active = EXCLUDED.active;

INSERT INTO activities (name)
VALUES
    ('Yoga'),
    ('Pilates'),
    ('Functional Training')
ON CONFLICT (name) DO NOTHING;

INSERT INTO package_types (name, class_credits, duration_days)
VALUES
    ('4 Classes', 4, 30),
    ('8 Classes', 8, 30),
    ('12 Classes', 12, 45)
ON CONFLICT (name) DO UPDATE
SET class_credits = EXCLUDED.class_credits,
    duration_days = EXCLUDED.duration_days;

INSERT INTO classes (
    activity_id,
    professor_id,
    starts_at,
    ends_at,
    capacity,
    cancelled
)
VALUES
    (
        (SELECT id FROM activities WHERE name = 'Yoga'),
        (SELECT id FROM users WHERE email = 'ana.professor@gymflow.test'),
        TIMESTAMPTZ '2026-10-05 18:00:00-03',
        TIMESTAMPTZ '2026-10-05 19:00:00-03',
        12,
        FALSE
    ),
    (
        (SELECT id FROM activities WHERE name = 'Pilates'),
        (SELECT id FROM users WHERE email = 'ana.professor@gymflow.test'),
        TIMESTAMPTZ '2026-10-06 10:00:00-03',
        TIMESTAMPTZ '2026-10-06 11:00:00-03',
        10,
        FALSE
    ),
    (
        (SELECT id FROM activities WHERE name = 'Functional Training'),
        (SELECT id FROM users WHERE email = 'ana.professor@gymflow.test'),
        TIMESTAMPTZ '2026-10-07 19:00:00-03',
        TIMESTAMPTZ '2026-10-07 20:00:00-03',
        15,
        FALSE
    )
ON CONFLICT (activity_id, professor_id, starts_at) DO UPDATE
SET ends_at = EXCLUDED.ends_at,
    capacity = EXCLUDED.capacity,
    cancelled = EXCLUDED.cancelled;

INSERT INTO member_packages (
    member_id,
    package_type_id,
    starts_on,
    expires_on,
    remaining_credits
)
VALUES
    (
        (SELECT id FROM users WHERE email = 'juan.member@gymflow.test'),
        (SELECT id FROM package_types WHERE name = '8 Classes'),
        DATE '2026-09-15',
        DATE '2026-10-15',
        6
    ),
    (
        (SELECT id FROM users WHERE email = 'laura.member@gymflow.test'),
        (SELECT id FROM package_types WHERE name = '4 Classes'),
        DATE '2026-09-20',
        DATE '2026-10-20',
        3
    )
ON CONFLICT (member_id, package_type_id, starts_on) DO UPDATE
SET expires_on = EXCLUDED.expires_on,
    remaining_credits = EXCLUDED.remaining_credits;

INSERT INTO class_reservations (
    class_id,
    member_package_id,
    cancelled,
    attended
)
VALUES
    (
        (
            SELECT c.id
            FROM classes c
            JOIN activities a ON a.id = c.activity_id
            WHERE a.name = 'Yoga'
              AND c.starts_at = TIMESTAMPTZ '2026-10-05 18:00:00-03'
        ),
        (
            SELECT mp.id
            FROM member_packages mp
            JOIN users u ON u.id = mp.member_id
            JOIN package_types pt ON pt.id = mp.package_type_id
            WHERE u.email = 'juan.member@gymflow.test'
              AND pt.name = '8 Classes'
              AND mp.starts_on = DATE '2026-09-15'
        ),
        FALSE,
        TRUE
    ),
    (
        (
            SELECT c.id
            FROM classes c
            JOIN activities a ON a.id = c.activity_id
            WHERE a.name = 'Pilates'
              AND c.starts_at = TIMESTAMPTZ '2026-10-06 10:00:00-03'
        ),
        (
            SELECT mp.id
            FROM member_packages mp
            JOIN users u ON u.id = mp.member_id
            JOIN package_types pt ON pt.id = mp.package_type_id
            WHERE u.email = 'laura.member@gymflow.test'
              AND pt.name = '4 Classes'
              AND mp.starts_on = DATE '2026-09-20'
        ),
        FALSE,
        FALSE
    )
ON CONFLICT (class_id, member_package_id) DO UPDATE
SET cancelled = EXCLUDED.cancelled,
    attended = EXCLUDED.attended;

COMMIT;
